document.addEventListener('DOMContentLoaded', function() {
    const calendarEl = document.getElementById('calendar');
    const roleManager = window.roleManager;
    
    // UI Elements
    const eventModal = document.getElementById('eventModal');
    const eventForm = document.getElementById('eventForm');
    const modalTitle = document.getElementById('eventModalTitle');
    const btnAddEvent = document.getElementById('btnAddEvent');
    const btnDeleteEvent = document.getElementById('btnDeleteEvent');
    const eventTypeSelect = document.getElementById('eventType');
    
    // Form Inputs
    const eventIdInput = document.getElementById('eventId');
    const eventTitleInput = document.getElementById('eventTitle');
    const eventDateInput = document.getElementById('eventDate');
    const eventTimeInput = document.getElementById('eventTime');
    const eventDescriptionInput = document.getElementById('eventDescription');
    const eventColorInput = document.getElementById('eventColor');
    
    // Role-based permissions
    const updatePermissions = () => {
        const role = roleManager.getCurrentRole();
        
        // Setup allowed event types for dropdown
        eventTypeSelect.innerHTML = '';
        const allowedTypes = [];
        
        if (role === 'admin' || role === 'hr') {
            allowedTypes.push('Holiday', 'Meeting', 'Birthday', 'Training', 'Interview', 'Notice', 'Leave');
            btnAddEvent.style.display = 'block';
        } else if (role === 'manager') {
            allowedTypes.push('Meeting', 'Interview');
            btnAddEvent.style.display = 'block';
        } else {
            // Employee cannot add events
            btnAddEvent.style.display = 'none';
        }
        
        allowedTypes.forEach(t => {
            const option = document.createElement('option');
            option.value = t;
            option.textContent = t;
            eventTypeSelect.appendChild(option);
        });
    };
    
    // Listen for role changes
    window.addEventListener('roleChanged', () => {
        updatePermissions();
        if (window.calendar) window.calendar.refetchEvents();
    });

    updatePermissions();

    // Initialize FullCalendar
    const calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',
        headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay'
        },
        events: async function(info, successCallback, failureCallback) {
            try {
                // Formatting dates to YYYY-MM-DD
                const startStr = info.start.toISOString().split('T')[0];
                const endStr = info.end.toISOString().split('T')[0];
                
                const response = await endpoints.calendar.getEvents({ startDate: startStr, endDate: endStr });
                if (response.success) {
                    successCallback(response.data);
                } else {
                    window.toast.show('Failed to load events', 'error');
                    failureCallback();
                }
            } catch (err) {
                console.error('Error fetching events:', err);
                failureCallback(err);
            }
        },
        eventClick: function(info) {
            const role = roleManager.getCurrentRole();
            const eventProps = info.event.extendedProps;
            const isAutoGenerated = ['Holiday', 'Birthday', 'Anniversary', 'Leave'].includes(eventProps.eventType);
            
            // Cannot edit auto-generated events directly from calendar, only user-created
            if (isAutoGenerated) {
                window.toast.show(`This is an auto-generated ${eventProps.eventType} and cannot be edited.`, 'info');
                return;
            }

            // Permissions check for editing
            const canEdit = (role === 'admin' || role === 'hr') || 
                            (role === 'manager' && ['Meeting', 'Interview'].includes(eventProps.eventType));

            if (!canEdit) {
                window.toast.show('You do not have permission to edit this event.', 'error');
                return;
            }

            openEventModal(info.event);
        }
    });
    
    calendar.render();
    window.calendar = calendar;

    // Default colors for event types
    const eventColors = {
        'Holiday': '#e74c3c',
        'Meeting': '#3788d8',
        'Birthday': '#9b59b6',
        'Training': '#34495e',
        'Interview': '#f1c40f',
        'Notice': '#7f8c8d',
        'Leave': '#f39c12'
    };

    window.handleEventTypeChange = () => {
        const type = eventTypeSelect.value;
        if (eventColors[type]) {
            eventColorInput.value = eventColors[type];
        }
    };

    window.openEventModal = (eventObj = null) => {
        eventForm.reset();
        
        if (eventObj) {
            modalTitle.textContent = 'Edit Event';
            eventIdInput.value = eventObj.extendedProps.eventId;
            eventTitleInput.value = eventObj.title;
            
            // Format Date
            if (eventObj.start) {
                eventDateInput.value = eventObj.startStr.split('T')[0];
                if (eventObj.startStr.includes('T')) {
                    eventTimeInput.value = eventObj.startStr.split('T')[1].substring(0, 5);
                }
            }
            
            eventTypeSelect.value = eventObj.extendedProps.eventType || 'Meeting';
            eventDescriptionInput.value = eventObj.extendedProps.description || '';
            eventColorInput.value = eventObj.backgroundColor || '#3788d8';
            
            btnDeleteEvent.style.display = 'block';
        } else {
            modalTitle.textContent = 'Add Event';
            eventIdInput.value = '';
            eventColorInput.value = '#3788d8';
            btnDeleteEvent.style.display = 'none';
        }
        
        eventModal.classList.add('active');
    };

    window.closeEventModal = () => {
        eventModal.classList.remove('active');
    };

    window.saveEvent = async () => {
        if (!eventForm.checkValidity()) {
            eventForm.reportValidity();
            return;
        }
        
        const payload = {
            title: eventTitleInput.value,
            description: eventDescriptionInput.value,
            eventDate: eventDateInput.value,
            eventTime: eventTimeInput.value || null,
            eventType: eventTypeSelect.value,
            color: eventColorInput.value,
            createdBy: roleManager.getCurrentEmployeeId() || null
        };

        const eventId = eventIdInput.value;
        try {
            let res;
            if (eventId) {
                res = await endpoints.calendar.update(eventId, payload);
            } else {
                res = await endpoints.calendar.create(payload);
            }

            if (res.success) {
                window.toast.show(res.message, 'success');
                closeEventModal();
                calendar.refetchEvents();
            } else {
                window.toast.show(res.error || 'Failed to save event', 'error');
            }
        } catch (e) {
            window.toast.show('An error occurred', 'error');
            console.error(e);
        }
    };

    window.deleteEvent = async () => {
        const eventId = eventIdInput.value;
        if (!eventId) return;

        if (confirm('Are you sure you want to delete this event?')) {
            try {
                const res = await endpoints.calendar.delete(eventId);
                if (res.success) {
                    window.toast.show(res.message, 'success');
                    closeEventModal();
                    calendar.refetchEvents();
                } else {
                    window.toast.show(res.error || 'Failed to delete event', 'error');
                }
            } catch (e) {
                window.toast.show('An error occurred', 'error');
                console.error(e);
            }
        }
    };
});
